# volume and persistent volume claim of `products`
apiVersion: v1
kind: PersistentVolume
metadata:
  name: products-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: products-storage
  hostPath:
    path: /data/volumes/products-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: products-storage
  resources:
    requests:
      storage: 1Gi