
# mongodb service and deployment
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mongodb-ratings
  name: mongodb-ratings
spec:
  ports:
    - name: "mongodb-ratings"
      port: 27017
      targetPort: 27017
  selector:
    service: mongodb-ratings
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: mongodb-ratings
  name: mongodb-ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb-ratings
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mongodb-ratings
    spec:
      containers:
        - image: mongo:4.4.6
          name: bookinfo-ratings-mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
          volumeMounts:
            - mountPath: /data/db
              name: ratings
      restartPolicy: Always
      volumes:
        - name: ratings
          persistentVolumeClaim:
            claimName: ratings-pvc
status: {}
---
