
# mongodb service and deployment
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-ratings
  name: mongodb-ratings
spec:
  ports:
    - name: "mongodb-ratings"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongodb-ratings
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-ratings
  name: mongodb-ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-ratings
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-ratings
    spec:
      containers:
        - image: mongo:4.4.6
          name: bookinfo-ratings-mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
          volumeMounts:
            - mountPath: /data/db
              name: ratings
      restartPolicy: Always
      volumes:
        - name: ratings
          persistentVolumeClaim:
            claimName: ratings-pvc
status: {}
---
