
# mongodb service and deployment
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mongodb-details
  name: mongodb-details
spec:
  ports:
    - name: "mongodb-details"
      port: 27017
      targetPort: 27017
  selector:
    service: mongodb-details
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: mongodb-details
  name: mongodb-details
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb-details
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mongodb-details
    spec:
      nodeName: h2.hotel.meshbench-pg0.clemson.cloudlab.us
      containers:
        - image: mongo:4.4.6
          name: bookinfo-details-mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
          volumeMounts:
            - mountPath: /data/db
              name: details
      restartPolicy: Always
      volumes:
        - name: details
          persistentVolumeClaim:
            claimName: details-pvc
status: {}
---