
##################################################################################################
# Reviews service and deployment
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
    service: reviews
spec:
  # sessionAffinity: ClientIP
  ports:
  - port: 8083
    name: reviews
  selector:
    app: reviews
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
  labels:
    account: reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v3
  labels:
    app: reviews
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      nodeName: h2.hotel.meshbench-pg0.clemson.cloudlab.us
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: xzhu0027/bookinfo_grpc:test
        command: ["/app/bookinfo"]
        args: ["reviews"]
        # imagePullPolicy: Always
        env:
        - name: REVIEWS_VERSION
          value: "v3"
        ports:
        - containerPort: 8083
---